<?php

namespace projet1Bundle\repository;

/**
 * Admin
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Admin extends \Doctrine\ORM\EntityRepository
{
}
