<?php

namespace projet1Bundle\repository;

/**
 * Commentaire
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire extends \Doctrine\ORM\EntityRepository
{
}
